### ISSUE TITLE
fails installing during dependencies

### ISSUE THREAD

**Issue by xenobc** [serverless/serverless-starter#15]
I am running Mac OS X 10.9.5 and node 4.4.1.  When I try to install serverless-starter I get the following error:
serverless project install serverless-starter

---

|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|**|  _**/|_____|**| |**|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v0.5.2
`-------'

Serverless: Installing Serverless Project "serverless-starter"...
Serverless: Downloading project and installing dependencies...
{ [Error: EEXIST: file already exists, link '/var/folders/k1/5jy56b2s4gbcczphc9pxxj2h0000gp/T/__sls_project_install_serverless-starter_1459544855741/node_modules' -> '/Users/jclayton/serverless_test/serverless-starter/node_modules']
  cause:
   { [Error: EEXIST: file already exists, link '/var/folders/k1/5jy56b2s4gbcczphc9pxxj2h0000gp/T/__sls_project_install_serverless-starter_1459544855741/node_modules' -> '/Users/jclayton/serverless_test/serverless-starter/node_modules']
     errno: -17,
     code: 'EEXIST',
     syscall: 'link',
     path: '/var/folders/k1/5jy56b2s4gbcczphc9pxxj2h0000gp/T/__sls_project_install_serverless-starter_1459544855741/node_modules',
     dest: '/Users/jclayton/serverless_test/serverless-starter/node_modules' },
  isOperational: true,
  errno: -17,
  code: 'EEXIST',
  syscall: 'link',
  path: '/var/folders/k1/5jy56b2s4gbcczphc9pxxj2h0000gp/T/__sls_project_install_serverless-starter_1459544855741/node_modules',
  dest: '/Users/jclayton/serverless_test/serverless-starter/node_modules' }

I have tried removing the path in the /var folder but it looks like this is generated for each install, then complains that it exists.

**Comment by gadams999** [comment]
Same issue, similar install (OSX 10.11.4, Node 4.3.2 via NVM).

```
Yak:jaws_test gadams$ serverless project install serverless-starter
 _______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v0.5.2
`-------'

Serverless: Installing Serverless Project "serverless-starter"...
Serverless: Downloading project and installing dependencies...
{ [Error: EEXIST: file already exists, link '/var/folders/s6/kltw03bj5sdbdvyt1nmt62pr0000gn/T/__sls_project_install_serverless-starter_1459641733242/node_modules' -> '/Users/gadams/dev/jaws_test/serverless-starter/node_modules']
  cause:
   { [Error: EEXIST: file already exists, link '/var/folders/s6/kltw03bj5sdbdvyt1nmt62pr0000gn/T/__sls_project_install_serverless-starter_1459641733242/node_modules' -> '/Users/gadams/dev/jaws_test/serverless-starter/node_modules']
     errno: -17,
     code: 'EEXIST',
     syscall: 'link',
     path: '/var/folders/s6/kltw03bj5sdbdvyt1nmt62pr0000gn/T/__sls_project_install_serverless-starter_1459641733242/node_modules',
     dest: '/Users/gadams/dev/jaws_test/serverless-starter/node_modules' },
  isOperational: true,
  errno: -17,
  code: 'EEXIST',
  syscall: 'link',
  path: '/var/folders/s6/kltw03bj5sdbdvyt1nmt62pr0000gn/T/__sls_project_install_serverless-starter_1459641733242/node_modules',
  dest: '/Users/gadams/dev/jaws_test/serverless-starter/node_modules' }
```

**Comment by jordanmack** [comment]
@xenobc @gadams999 I was also able to replicate this on a clean system with v0.5.2. I've put together some [Alternative Install](https://github.com/serverless/serverless-starter#alternative-install) instructions that can be used while we're waiting for resolution on this issue.

**Comment by jordanmack** [comment]
Serverless Framework v1.0 has now been released, and `project install` is no longer used in this way. Closing since it is no longer applicable.
